language: java
script: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
branches:
  only:
    - master
    
deploy:
  provider: cloudfoundry
  edge: true
  api: $CF_API
  username: $CF_USER
  password: $CF_PASS
  organization: $CF_ORG
  space: $CF_ENV 