	DROP TABLE PROVIDER;
	
	DROP TABLE QUALITYSTARRATING;
	
	DROP TABLE ADDRESS;
	
	DROP TABLE PROVIDERTYPE;
	
	CREATE TABLE QUALITYSTARRATING
	(
	RATINGID        INT NOT NULL,
	DESCRIPTION TEXT,
    PRIMARY KEY (RATINGID)
	);
	
	CREATE TABLE ADDRESS
	(
	ADDRESSID        INT NOT NULL,
	CITY TEXT,
	COUNTYNUMBER INT NOT NULL,
	COUNTY TEXT,
	ZIPCODE INT,
	LATITUDE DOUBLE PRECISION,
	LONGITUDE DOUBLE PRECISION,
	PRIMARY KEY (ADDRESSID)
	);
	
	CREATE TABLE PROVIDERTYPE
	(
	TypeId        INT NOT NULL,
	Description TEXT,
	PRIMARY KEY (TypeId)
	);
	
	CREATE TABLE PROVIDER
	(
	PROVIDERID        INT NOT NULL,
	Name    TEXT,
	LICENSETYPE      TEXT,
	TypeId     INT NOT NULL,
	ADDRESSID     INT NOT NULL,
	RATINGID       INT NOT NULL,
	Capacity INT NOT NULL,
	PHONENUMBER 	TEXT,
	PRIMARY KEY (PROVIDERID),
	FOREIGN KEY (TYPEID) REFERENCES PROVIDERTYPE (TypeId),
	FOREIGN KEY (ADDRESSID) REFERENCES ADDRESS (ADDRESSID),
	FOREIGN KEY (RATINGID) REFERENCES QUALITYSTARRATING (RATINGID)
	);
	
	COMMIT;
	
	CREATE INDEX addressId_idx_provider ON PROVIDER (addressId);
	CREATE INDEX typeId_idx_provider ON PROVIDER (typeId);
	CREATE INDEX ratingId_idx_provider ON PROVIDER (ratingId);
	CREATE INDEX name_idx_provider ON PROVIDER (name);
	CREATE INDEX county_idx_address ON ADDRESS (county);
	CREATE INDEX city_idx_address ON ADDRESS (city);

	COMMIT;