INSERT INTO PROVIDERTYPE  (TYPEID, DESCRIPTION)  VALUES(' 2','Slot Contractor');
INSERT INTO PROVIDERTYPE  (TYPEID, DESCRIPTION)  VALUES(' 3','Group Home');
INSERT INTO PROVIDERTYPE  (TYPEID, DESCRIPTION)  VALUES(' 4','Center');
INSERT INTO PROVIDERTYPE  (TYPEID, DESCRIPTION)  VALUES(' 5','Non-Relative In-Home');
INSERT INTO PROVIDERTYPE  (TYPEID, DESCRIPTION)  VALUES(' 6','Relative In-Home');
INSERT INTO PROVIDERTYPE  (TYPEID, DESCRIPTION)  VALUES(' 7','Non-Relative Out-of-Home');
INSERT INTO PROVIDERTYPE  (TYPEID, DESCRIPTION)  VALUES(' 8','Relative Out-of-Home');

COMMIT;
