INSERT INTO QUALITYSTARRATING  (RATINGID, DESCRIPTION)  VALUES(' 0','Not Rated');
INSERT INTO QUALITYSTARRATING  (RATINGID, DESCRIPTION)  VALUES(' 1','Low');
INSERT INTO QUALITYSTARRATING  (RATINGID, DESCRIPTION)  VALUES(' 2','Average');
INSERT INTO QUALITYSTARRATING  (RATINGID, DESCRIPTION)  VALUES(' 3','Good');
INSERT INTO QUALITYSTARRATING  (RATINGID, DESCRIPTION)  VALUES(' 4','Very Good');
INSERT INTO QUALITYSTARRATING  (RATINGID, DESCRIPTION)  VALUES(' 5','Excellent');

COMMIT;
