DROP TABLE POC_TASK.PROVIDER;

CREATE TABLE POC_TASK.PROVIDER
	(
	PROVIDERID        NUMBER (19) NOT NULL,
	PROVIDERNAME    VARCHAR2 (200),
	LICENSETYPE      VARCHAR2 (200),
	PROVIDERTYPEID     NUMBER (19) NOT NULL,
	ADDRESSID     NUMBER(19) NOT NULL,
	RATINGID       NUMBER(19) NOT NULL,
	PROVIDERCAPACITY NUMBER(19) NOT NULL,
	PHONENUMBER 	VARCHAR2 (200),
	PRIMARY KEY (PROVIDERID),
	FOREIGN KEY (PROVIDERTYPEID) REFERENCES POC_TASK.PROVIDERTYPE (PROVIDERTYPEID),
	FOREIGN KEY (ADDRESSID) REFERENCES POC_TASK.ADDRESS (ADDRESSID),
	FOREIGN KEY (RATINGID) REFERENCES POC_TASK.QUALITYSTARRATING (RATINGID)
	);
	
	INSERT INTO POC_TASK.PROVIDER VALUES (1,'Abelina Martinez','UNLICENSED',5,4,0,5,'205-398-3018');
	INSERT INTO POC_TASK.PROVIDER VALUES (2,'Abigail  Rodriguez','UNLICENSED',6,5,0,5,'205-454-3601');
	INSERT INTO POC_TASK.PROVIDER VALUES (3,'K Street Learning Center LLC','LICENSED',2,6,0,30,'205-698-0401');
	INSERT INTO POC_TASK.PROVIDER VALUES (4,'Abigail Burross','UNLICENSED',7,7,0,5,'214-580-6261');
	INSERT INTO POC_TASK.PROVIDER VALUES (5,'Abigail Khan','UNLICENSED',8,8,0,5,'217-503-0764');
	INSERT INTO POC_TASK.PROVIDER VALUES (6,'Abigail Moore','UNLICENSED',5,9,0,5,'225-620-7470');	  
	
	COMMIT;
	